### ISSUE TITLE
Can I bump a version without making a git tag?

### ISSUE THREAD

**Issue by sethladd** [seaneagan/den#27]
If so, can you show that in the README?

**Comment by seaneagan** [comment]
I assume you want to bypass the commit altogether in that case?  A `--no-git` flag or similar sgtm.

**Comment by sethladd** [comment]
yes, looking to *just* bump and not commit. at least, as an option. `--no-git` would be great.

Why? Because I want to verify what the tool did, before it commits.

**Comment by seaneagan** [comment]
It could be a --confirm option instead, or it could confirm by default, and there could be --force.  Thoughts?

**Comment by sethladd** [comment]
personally, I wouldn't add any git tag. just because I want to bump the version doesn't mean I want to also create a tag. In fact, this is blocking me from using den.

**Comment by seaneagan** [comment]
I think the right default is to do the tagged version commit, since it encodes the best practice of tagging your versions.  I took a lot of inspiration from the [npm version ...](https://docs.npmjs.com/cli/version) command.  I just didn't get around to implementing the flag to disable it yet :).  I should be able to get to it early next week.

**Comment by sethladd** [comment]
generating a git tag is good practice, but I don't necessarily always want to do it the instant I bump the version. I might be bumping it as part of a larger workflow to get a release ready. Having a flag to disable would be sufficient. Thanks!

**Comment by seaneagan** [comment]
@sethladd Use `den bump patch --no-git` let me know if you have any issues with it.

**Comment by sethladd** [comment]
Great, thanks!
